/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/lake/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake Sources */
        get: operations["lake_sources_lake_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake List */
        get: operations["lake_list_lake_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/object": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake Object */
        get: operations["lake_object_lake_object_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/object/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake Structure */
        get: operations["lake_structure_lake_object_structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/object/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake Rows */
        get: operations["lake_rows_lake_object_rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/object/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake Text */
        get: operations["lake_text_lake_object_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/object/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lake Signed Url */
        get: operations["lake_signed_url_lake_object_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lake/object/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lake Content
         * @description The file's bytes, with HTTP Range support (pdf.js reads PDFs in ranges).
         */
        get: operations["lake_content_lake_object_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tables */
        get: operations["list_tables_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table Detail */
        get: operations["table_detail_tables__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{name}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table Rows */
        get: operations["table_rows_tables__name__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{name}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Table Lineage
         * @description The raw files that fed a table (`lake_processed`); SQL datasets have none of their own.
         */
        get: operations["table_lineage_tables__name__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_pipeline_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DatasetRef */
        DatasetRef: {
            /** Name */
            name: string;
            /**
             * Target
             * @enum {string}
             */
            target: "postgres" | "bigquery";
            /** Mode */
            mode: string;
            /** Loaded */
            loaded: boolean;
            /** Rows */
            rows?: number | null;
            /**
             * Rows Estimated
             * @default false
             */
            rows_estimated: boolean;
        };
        /** FormatCount */
        FormatCount: {
            /** Extension */
            extension: string;
            /** Files */
            files: number;
        };
        /** GridColumn */
        GridColumn: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number" | "date" | "boolean" | "json" | "geometry";
            /** Source Type */
            source_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Lake */
            lake: string;
            /** Database */
            database: boolean;
        };
        /** JsonNode */
        JsonNode: {
            /** Key */
            key?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "object" | "array" | "string" | "number" | "boolean" | "null";
            /** Value */
            value?: string | null;
            /** Length */
            length?: number | null;
            /** Children */
            children?: components["schemas"]["JsonNode"][] | null;
        };
        /** LakeFolder */
        LakeFolder: {
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Files */
            files?: number | null;
            /** Bytes */
            bytes?: number | null;
            /** Last Fetched At */
            last_fetched_at?: string | null;
        };
        /** LakeListing */
        LakeListing: {
            /** Prefix */
            prefix: string;
            /** Folders */
            folders: components["schemas"]["LakeFolder"][];
            /** Objects */
            objects: components["schemas"]["LakeObject"][];
            /** Total Objects */
            total_objects: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** LakeObject */
        LakeObject: {
            /** Key */
            key: string;
            /** Source Id */
            source_id: string;
            /** Dt */
            dt: string;
            /** File */
            file: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "sheet" | "text" | "parquet" | "json" | "geojson" | "zip" | "pdf" | "slides" | "document" | "html" | "other";
            /** Bytes */
            bytes: number;
            /** Sha256 */
            sha256?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /** Url */
            url?: string | null;
            /** Source Page */
            source_page?: string | null;
            /** Content Type */
            content_type?: string | null;
            /** Http Status */
            http_status?: number | null;
            /** Doc Id */
            doc_id?: string | null;
            /** Report Type Id */
            report_type_id?: string | null;
            /** Etag */
            etag?: string | null;
            /** Last Modified */
            last_modified?: string | null;
            /**
             * Meta
             * @default {}
             */
            meta: {
                [key: string]: unknown;
            };
        };
        /** LakeTotals */
        LakeTotals: {
            /** Sources */
            sources: number;
            /** Files */
            files: number;
            /** Bytes */
            bytes: number;
        };
        /** LineagePage */
        LineagePage: {
            /** Items */
            items: components["schemas"]["LineageRow"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** LineageResponse */
        LineageResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["LineagePage"];
        };
        /** LineageRow */
        LineageRow: {
            /** Raw Key */
            raw_key: string;
            /** Sha256 */
            sha256: string;
            /** Version */
            version: number;
            /** Rows */
            rows?: number | null;
            /**
             * Processed At
             * Format: date-time
             */
            processed_at: string;
        };
        /** ListingResponse */
        ListingResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["LakeListing"];
        };
        /** Meta */
        Meta: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Data As Of */
            data_as_of?: string | null;
            /** Model Run Id */
            model_run_id?: string | null;
            /**
             * Simulated
             * @default false
             */
            simulated: boolean;
            /** Sources */
            sources?: string[];
        };
        /** ObjectDetail */
        ObjectDetail: {
            object: components["schemas"]["LakeObject"];
            source: components["schemas"]["SourceRef"];
            /** Viewer */
            viewer: string;
            /** Previewable */
            previewable: boolean;
            /** Datasets */
            datasets: components["schemas"]["DatasetRef"][];
            /** Processed */
            processed: components["schemas"]["ProcessedRef"][];
            /** Other Snapshots */
            other_snapshots: components["schemas"]["SnapshotRef"][];
        };
        /** ObjectResponse */
        ObjectResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["ObjectDetail"];
        };
        /** ObjectStructure */
        ObjectStructure: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "sheet" | "text" | "parquet" | "json" | "geojson" | "zip" | "pdf" | "slides" | "document" | "html" | "other";
            /** Viewer */
            viewer: string;
            /**
             * Too Large
             * @default false
             */
            too_large: boolean;
            /** Note */
            note?: string | null;
            /** Sheets */
            sheets?: components["schemas"]["SheetInfo"][] | null;
            /** Members */
            members?: components["schemas"]["ZipMember"][] | null;
            /** Columns */
            columns?: components["schemas"]["GridColumn"][] | null;
            /** Row Count */
            row_count?: number | null;
            /** Delimiter */
            delimiter?: string | null;
            /** Tabular Path */
            tabular_path?: string | null;
            json_tree?: components["schemas"]["JsonNode"] | null;
        };
        /** ObjectText */
        ObjectText: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "sheet" | "text" | "parquet" | "json" | "geojson" | "zip" | "pdf" | "slides" | "document" | "html" | "other";
            /** Blocks */
            blocks: components["schemas"]["TextBlock"][];
        };
        /** ProcessedRef */
        ProcessedRef: {
            /** Dataset */
            dataset: string;
            /** Version */
            version: number;
            /** Rows */
            rows?: number | null;
            /**
             * Processed At
             * Format: date-time
             */
            processed_at: string;
            /** Current */
            current: boolean;
        };
        /**
         * RowsPage
         * @description One block of rows. `total` comes only when the request asks for it (`with_summary=true`).
         */
        RowsPage: {
            /** Columns */
            columns: components["schemas"]["GridColumn"][];
            /** Rows */
            rows: (string | number | boolean | null)[][];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total?: number | null;
            /**
             * Total Estimated
             * @default false
             */
            total_estimated: boolean;
        };
        /** RowsResponse */
        RowsResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["RowsPage"];
        };
        /** Run */
        Run: {
            /** Run Id */
            run_id: string;
            /** Source */
            source: string;
            /** Stage */
            stage: string;
            /** Dag Id */
            dag_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Status */
            status: string;
            /** Rows */
            rows?: number | null;
            /** Files */
            files?: number | null;
            /** Files Skipped */
            files_skipped?: number | null;
            /** Bytes */
            bytes?: number | null;
            /** Error */
            error?: string | null;
        };
        /** RunRef */
        RunRef: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** RunsPage */
        RunsPage: {
            /** Items */
            items: components["schemas"]["Run"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** RunsResponse */
        RunsResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["RunsPage"];
        };
        /** SheetInfo */
        SheetInfo: {
            /** Name */
            name: string;
            /** Rows */
            rows?: number | null;
            /** Columns */
            columns?: number | null;
        };
        /** SignedUrl */
        SignedUrl: {
            /** Url */
            url: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** SignedUrlResponse */
        SignedUrlResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["SignedUrl"];
        };
        /** SnapshotRef */
        SnapshotRef: {
            /** Dt */
            dt: string;
            /** Key */
            key: string;
            /** File */
            file: string;
            /** Bytes */
            bytes: number;
        };
        /** SourceRef */
        SourceRef: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Publisher */
            publisher?: string | null;
            /** Upstream Url */
            upstream_url?: string | null;
        };
        /** SourceSummary */
        SourceSummary: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Group */
            group: string;
            /** Publisher */
            publisher?: string | null;
            /** Description */
            description?: string | null;
            /** Upstream Url */
            upstream_url?: string | null;
            /** Catalog Id */
            catalog_id?: string | null;
            /** Schedule */
            schedule?: string | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Files */
            files: number;
            /** Bytes */
            bytes: number;
            /** Snapshots */
            snapshots: number;
            /** First Dt */
            first_dt?: string | null;
            /** Last Dt */
            last_dt?: string | null;
            /** Last Fetched At */
            last_fetched_at?: string | null;
            /** Formats */
            formats: components["schemas"]["FormatCount"][];
            /** Datasets */
            datasets: components["schemas"]["DatasetRef"][];
            /** Last Runs */
            last_runs: components["schemas"]["RunRef"][];
        };
        /** SourcesData */
        SourcesData: {
            /** Bucket */
            bucket: string;
            /**
             * Index Built At
             * Format: date-time
             */
            index_built_at: string;
            totals: components["schemas"]["LakeTotals"];
            /** Items */
            items: components["schemas"]["SourceSummary"][];
        };
        /** SourcesResponse */
        SourcesResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["SourcesData"];
        };
        /** StructureResponse */
        StructureResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["ObjectStructure"];
        };
        /** TableColumn */
        TableColumn: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number" | "date" | "boolean" | "json" | "geometry";
            /** Source Type */
            source_type?: string | null;
            /** Position */
            position: number;
            /** Nullable */
            nullable: boolean;
            /**
             * Is Key
             * @default false
             */
            is_key: boolean;
        };
        /** TableDetail */
        TableDetail: {
            /** Name */
            name: string;
            /**
             * Engine
             * @enum {string}
             */
            engine: "postgres" | "bigquery";
            /** Location */
            location: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dataset" | "system" | "unregistered";
            /** Sources */
            sources: string[];
            /** Mode */
            mode?: string | null;
            /** Description */
            description?: string | null;
            /** Declared */
            declared: boolean;
            /** Loaded */
            loaded: boolean;
            /** Rows */
            rows?: number | null;
            /**
             * Rows Estimated
             * @default false
             */
            rows_estimated: boolean;
            /** Bytes */
            bytes?: number | null;
            /** Columns */
            columns: components["schemas"]["TableColumn"][];
            /**
             * Key Columns
             * @default []
             */
            key_columns: string[];
            /** Partition Field */
            partition_field?: string | null;
            /**
             * Cluster Fields
             * @default []
             */
            cluster_fields: string[];
            /**
             * Derived
             * @default false
             */
            derived: boolean;
        };
        /** TableResponse */
        TableResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["TableDetail"];
        };
        /** TableSummary */
        TableSummary: {
            /** Name */
            name: string;
            /**
             * Engine
             * @enum {string}
             */
            engine: "postgres" | "bigquery";
            /** Location */
            location: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dataset" | "system" | "unregistered";
            /** Sources */
            sources: string[];
            /** Mode */
            mode?: string | null;
            /** Description */
            description?: string | null;
            /** Declared */
            declared: boolean;
            /** Loaded */
            loaded: boolean;
            /** Rows */
            rows?: number | null;
            /**
             * Rows Estimated
             * @default false
             */
            rows_estimated: boolean;
            /** Bytes */
            bytes?: number | null;
        };
        /** TablesData */
        TablesData: {
            /** Items */
            items: components["schemas"]["TableSummary"][];
        };
        /** TablesResponse */
        TablesResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["TablesData"];
        };
        /** TextBlock */
        TextBlock: {
            /** Title */
            title?: string | null;
            /** Text */
            text: string;
        };
        /** TextResponse */
        TextResponse: {
            meta: components["schemas"]["Meta"];
            data: components["schemas"]["ObjectText"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ZipMember */
        ZipMember: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "sheet" | "text" | "parquet" | "json" | "geojson" | "zip" | "pdf" | "slides" | "document" | "html" | "other";
            /** Bytes */
            bytes: number;
            /** Compressed Bytes */
            compressed_bytes: number;
            /** Modified */
            modified?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    lake_sources_lake_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_list_lake_list_get: {
        parameters: {
            query?: {
                /** @description Folder to list, ending in '/', or '' for the bucket root */
                prefix?: string;
                /** @description Keep only names containing this text (case-insensitive) */
                q?: string;
                /** @description Under raw/, list every object below the prefix */
                recursive?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_object_lake_object_get: {
        parameters: {
            query: {
                /** @description Object key, e.g. raw/source=ercot_gis/dt=2026-08-01/<file> */
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_structure_lake_object_structure_get: {
        parameters: {
            query: {
                key: string;
                member?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_rows_lake_object_rows_get: {
        parameters: {
            query: {
                key: string;
                /** @description A file inside a zip */
                member?: string | null;
                /** @description Spreadsheet sheet; the first one by default */
                sheet?: string | null;
                offset?: number;
                limit?: number;
                /** @description Also return the total row count */
                with_summary?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_text_lake_object_text_get: {
        parameters: {
            query: {
                key: string;
                member?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_signed_url_lake_object_url_get: {
        parameters: {
            query: {
                key: string;
                /** @description Ask the browser to save the file instead of opening it */
                download?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lake_content_lake_object_content_get: {
        parameters: {
            query: {
                key: string;
                member?: string | null;
            };
            header?: {
                Range?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tables_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_detail_tables__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_rows_tables__name__rows_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Column to sort by */
                sort?: string | null;
                desc?: boolean;
                /** @description column:op:value, repeatable. Ops: eq ne contains starts in gte lte gt lt between null notnull; `in` and `between` join values with U+001F */
                filter?: string[];
                /** @description Also return the total (exact when it fits in 6 s) */
                with_summary?: boolean;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_lineage_tables__name__lineage_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_pipeline_runs_get: {
        parameters: {
            query?: {
                source?: string | null;
                /** @description raw or process */
                stage?: string | null;
                /** @description running, success, partial, failed or abandoned */
                status?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
